const builtInSort = require('./built-in-sort')
const bubbleSort = require('./bubble-sort')
const selectionSort = require('./selection-sort')
const quickSort = require('./quick-sort')
const inPlaceQuickSort = require('./in-place-quick-sort')
const { createArray } = require('../utils')

const origin = createArray(10 * 2)
// const origin = [0, 9, 6, 1, 7]
console.log('origin:', origin)

const builtIn = origin.slice()
console.time('builtInSort')
builtInSort(builtIn)
console.timeEnd('builtInSort')
console.log('sorted:', builtIn)

const bubble = origin.slice()
console.time('bubbleSort')
bubbleSort(bubble)
console.timeEnd('bubbleSort')
console.log('sorted:', bubble)

const selection = origin.slice()
console.time('selectionSort')
selectionSort(selection)
console.timeEnd('selectionSort')
console.log('sorted:', selection)

const quick = origin.slice()
console.time('quickSort')
quickSort(quick)
console.timeEnd('quickSort')
console.log('sorted:', quickSort(quick))

const inPlaceQuick = origin.slice()
console.time('inPlaceQuickSort')
inPlaceQuickSort(inPlaceQuick)
console.timeEnd('inPlaceQuickSort')
console.log('sorted:', inPlaceQuick)
